version: '3.3'

services:
  db: # Esse será o nome do container
    image: mysql:8 # FROM mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always # Garante que as att persista no arquivo
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: slds
      MYSQL_PASSWORD: secret

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: slds
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}